### ISSUE TITLE
network.py error

### ISSUE THREAD

**Issue by beckw** [titu1994/Neural-Style-Transfer#14]
Hi there !
I've downloaded your Neural-Style_Transfer,and try to transfer some pictures. but got an error while computing.
could you help to take a look, thanks a lot.
[capture](https://cloud.githubusercontent.com/assets/23051388/19681027/74b1adce-9ada-11e6-83b1-a083b369862b.JPG)

**Comment by titu1994** [comment]
If you're in Windows, its easier to use the Script Helper program. It's in the releases tab, or in the script_helper folder if you downloaded the entire repo. 

It ensures correct syntax in executing the script and makes it much easier to perform style transfers.

**Comment by titu1994** [comment]
As to the error, its caused by "D:/test". You have to provide a prefix of the image:

So if D:/test is your test image directory, you need to provide the final path as "D:/test/temp1_"

**Comment by beckw** [comment]
I would like to use the Script Helper, and have tried it. it also doesn't work to me. I saw the command window start to using Theano and load model then the window disappeared. but i got a screen shot when it's going off.
![capture02](https://cloud.githubusercontent.com/assets/23051388/19682470/578c807e-9ae0-11e6-9732-7cb466ab38f9.JPG)
![capture3](https://cloud.githubusercontent.com/assets/23051388/19682555/bb9e44ee-9ae0-11e6-895c-df3f78158da9.JPG)
did i make a mistake while setup Environment?

**Comment by titu1994** [comment]
@beckw Try doing this : `pip install --upgrade git+https://github.com/Theano/Theano.git`

That will install and upgrade theano from github to the latest version. Also, your error from before is fixed. This is a new error caused by either an old theano version or using Theano with CPU mode without BLAS libraries.

Edit:
If such an error occurs, it is simpler to use the "Copy Arguments to Clipboard" button, which you can then paste into the cmd to see the error. Then you can paste the errors.

Example after copying the command arguments:
`python network.py <-- paste here and just execute -->`. It will show a long line of many arguments but that is fine.

**Comment by beckw** [comment]
@titu1994 I've used the command line to upgraded Theano to 0.90, still get the error:
![capture4](https://cloud.githubusercontent.com/assets/23051388/19716947/da11b806-9b90-11e6-945a-80bbcb293c44.JPG)
FYI,I got some difference between your guide when I was installing cuDNN. I didn't see the sub-folder"cuda" into the CUDA directory after install CUDA7.5. So, when I extract cuDNN into the CUDA directory, it did not overwrite any files. 
Is that a problem? 
thanks

**Comment by titu1994** [comment]
@beckw I should have made the guide a bit clearer on that. 

Once you extract the cudnn folder, there should be 3 sub folders inside the cuda folder. Copy those 3 sub folders and paste them in the CUDA 7.5 folder which has many folders. 

It should then override the "bin", "lib" and "include" folders if I remember correctly. This activates cuDNN with CUDA

**Comment by beckw** [comment]
@titu1994 I actually did that and added system variables
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
CUDNN_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5
have no idea why still doesn't work?

**Comment by titu1994** [comment]
@beckw Did you write a .theanorc.txt file in your home directory with the given settings? In your earlier screenshot, it seems that Theano is still using your CPU. 

When you use theano in GPU mode with cuDNN, it should show the a few startup lines like : 

```
Using Theano backend
Using GPU device 0: GeForce GTX 980M (CNMEM is enabled with initial size: 80% of memory, cuDNN 5103)
```

You have to follow the final few steps to setup the .theanorc.txt in windows home directory : `C:/Users/{Your Name}/`

**Comment by beckw** [comment]
sorry, my fault! missing the first . when creating the .theanorc.txt
now it start using GPU.
but got another new error : (
![capture5](https://cloud.githubusercontent.com/assets/23051388/19724506/40d9af40-9bb3-11e6-99d0-17121da60fa6.JPG)

**Comment by titu1994** [comment]
@beckw No problem. Do you have more than 1 CUDA installed ? As in CUDA 7.5 and 8 at the same time? This is usually caused then.

If not, then see if you overwrote the cuda files with the cudnn files.

**Comment by beckw** [comment]
@titu1994 I only have CUDA7.5 installed. and copied files like below:
The content of \cudnn-7.5-windows7-x64-v5.0-ga\cuda\bin  To C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin
The content of \cudnn-7.5-windows7-x64-v5.0-ga\cuda\include To C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include
The content of \cudnn-7.5-windows7-x64-v5.0-ga\cuda\lib\x64 To C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64
Also add these two system variable follow your guide
![capture06](https://cloud.githubusercontent.com/assets/23051388/19756093/c9347b74-9c4c-11e6-9c7b-9dbc45a6ca62.JPG)

**Comment by titu1994** [comment]
@beckw 
I made a mistake in the guide, the CUDNN_PATH must match the CUDA_PATH, since you are overwriting the files in CUDA. So try setting CUDNN_PATH to the CUDA_PATH.

If that still doesnt work, could you try editing the .theanorc.txt file to remove the line saying `optimizer_including=cudnn`?

This may be he problem. If it does run, make sure to check that when running the program it still gives the end part: 

```
(CNMEM is enabled with initial size: 80% of memory, cuDNN 5103)
```

**Comment by beckw** [comment]
@titu1994 I've noticed that might be a mistake about CUDNN_PATH in the guide, so I already set both them  same.
I have also tried to remove the line: `optimizer_including=cudnn`  and  add `cudnn=1.0` at the bottom in the .theanorc.txt file.
It still saying  `
(CNMeM is enabled with initial size: 80.
0% of memory, cuDNN not available)
`

**Comment by titu1994** [comment]
@beckw Hmm I don't know what's causing this. For some reason Theano is not able to detect cuDNN. The flag `optimizer_including=cudnn`  is to ensure that theano runs only with cudnn enabled, otherwise crash fast. The fact that Theano is saying cudnn not available means that it can't find cudnn inside cuda for some reason. 

Btw, use cudnn=0.8 at max. Using 100 % of gpu memory usually crashes theano because it cannot allocate the memory required by Windows to render the screen.

In any case, cuDNN is needed mainly for the INetwork.py script, since it uses every single layer of the VGG 16 or 19 network which is computationally extremely expensive. You can use the Network.py script instead which uses only 5 layers out of the 16 or 19 to run the program, though quality will be reduced.

**Comment by beckw** [comment]
@titu1994 It works after reinstall CUDA and cuDNN.
Great thanks all your help!! : )

**Comment by titu1994** [comment]
@beckw No problem. Glad it finally worked.
